### ISSUE TITLE
ValueError while running code

### ISSUE THREAD

**Issue by nikhilpinnaparaju** [bogatyy/cs224d#3]
Hi, I am trying to run the 'rnn_dynamic_graph.py' file but am getting a value error while doing so. 
![err](https://user-images.githubusercontent.com/25135708/47967202-dfcd2780-e080-11e8-909b-4b68d9770561.png)
I am running "python rnn_dynamic_graph.py" on terminal. Is there something I am doing wrong?

**Comment by bogatyy** [comment]
What is your TensorFlow version? The code corresponds to a pretty old one (TF 0.8) and might no longer be compatible.

Consider sending a patch if you fix the issue!
