### ISSUE TITLE
Licence info for Assignment code

### ISSUE THREAD

**Issue by Alanapiereid** [bogatyy/cs224d#5]
Just interested in (and impressed by) Assignment 3.
I take it this was your own assignment work from Stanford? Have you thought about adding a licence?

Thanks

**Comment by bogatyy** [comment]
Hi Alan! Glad you liked it. It is indeed my own work. Added an MIT license (AFAICT it is the most permissive, compared to say GPL, but let me know if you need any other permissions to use this)
